import base64
import urllib.parse
import re
from pathlib import Path
from typing import Dict, Any, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from pydantic import BaseModel
from jinja2 import Environment, FileSystemLoader
from weasyprint import HTML

app = FastAPI(title="Aura PDF Engine")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Directory mapping based on your local project structure
BASE_DIR = Path(__file__).parent
TEMPLATES_DIR = BASE_DIR / "templates"
MEDIA_DIR = BASE_DIR / "media"

jinja_env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)))

class GeneratePdfRequest(BaseModel):
    intake: Dict[str, Any]
    raw_ai_text: str

def get_logo_base64() -> Optional[str]:
    # Looks for your specific logo.jpg in the media folder
    logo_path = MEDIA_DIR / "logo.jpg"
    if logo_path.exists():
        with open(logo_path, "rb") as image_file:
            return base64.b64encode(image_file.read()).decode("utf-8")
    return None

def parse_workout_response(raw_text: str) -> Dict[str, Any]:
    # Extracts the specific sections generated by the Gemini master prompt
    def extract_section(tag: str, default: str = "") -> str:
        pattern = rf"\[SECTION:\s*{tag}\](.*?)(?=\[SECTION:|\Z)"
        match = re.search(pattern, raw_text, re.DOTALL | re.IGNORECASE)
        return match.group(1).strip() if match else default

    analysis = extract_section("ANALYSIS", "Analysis unavailable.")
    warmup = extract_section("WARMUP", "Dynamic warm-up recommended.")
    workouts_raw = extract_section("WORKOUTS", "")
    progression = extract_section("PROGRESSION", "Apply progressive overload.")

    days = []
    current_day = None

    for line in workouts_raw.splitlines():
        line = line.strip()
        if not line:
            continue

        if line.upper().startswith("DAY "):
            clean_title = re.sub(r"[#*]", "", line).strip()
            current_day = {"title": clean_title, "exercises": []}
            days.append(current_day)
        elif current_day and ("|" in line or "sets" in line.lower()):
            # 1. Strip the "Exercise X:" prefix from the Gemini output
            clean_line = re.sub(r"^Exercise\s*\d*:\s*", "", line, flags=re.I).strip()

            # 2. Extract the Tip/Cue and remove the word "Cue:"
            cue = ""
            cue_match = re.search(r"(?:Cue|Tips?)\s*:?\s*([^|]*)", clean_line, re.I)
            if cue_match:
                cue = cue_match.group(1).strip()
                clean_line = clean_line.replace(cue_match.group(0), "")

            # 3. Extract the Rest time and remove the word "Rest:"
            rest = ""
            rest_match = re.search(r"Rest\s*:?\s*([^|]*)", clean_line, re.I)
            if rest_match:
                rest = rest_match.group(1).strip()
                clean_line = clean_line.replace(rest_match.group(0), "")

            # 4. Split what is left (Name and Sets/Reps)
            parts = [p.strip() for p in clean_line.split("|") if p.strip()]
            ex_name = parts[0] if parts else "Exercise"
            reps_raw = parts[1] if len(parts) > 1 else ""

            current_day["exercises"].append({
                "name": ex_name,
                "sets_reps": reps_raw,
                "rest": rest,
                "tip": cue,
                "video_query": urllib.parse.quote(f"{ex_name} exercise form demo")
            })

    return {
        "analysis": analysis,
        "warmup": warmup,
        "days": days,
        "progression": progression
    }

@app.post("/api/generate-pdf")
async def generate_pdf_endpoint(request: GeneratePdfRequest):
    parsed_sections = parse_workout_response(request.raw_ai_text)
    logo_base64 = get_logo_base64()

    # Apply the parsed data to your HTML/CSS template
    template = jinja_env.get_template("pdf_template.html")
    rendered_html = template.render(
        intake=request.intake,
        sections=parsed_sections,
        logo_base64=logo_base64
    )

    # Use WeasyPrint to draw the physical PDF in server memory
    pdf_bytes = HTML(string=rendered_html).write_pdf()

    # Return the raw PDF binary directly to Google Apps Script
    return Response(
        content=pdf_bytes,
        media_type="application/pdf"
    )